//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Бригада.
    /// </summary>
    // *** Start programmer edit section *** (Бригада CustomAttributes)

    // *** End programmer edit section *** (Бригада CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БригадаE", new string[] {
            "начало as \'Сформирована с:\'",
            "конец as \'по:\'",
            "назначение as \'Назначение\'"})]
    [AssociatedDetailViewAttribute("БригадаE", "СоставБриг", "СоставБригE", true, "", "Состав бригады", true, new string[] {
            ""})]
    [View("БригадаL", new string[] {
            "начало as \'Начало\'",
            "конец as \'Конец\'",
            "назначение as \'Назначение\'"})]
    public class Бригада : ICSSoft.STORMNET.DataObject
    {
        
        private string fконец;
        
        private string fначало;
        
        private string fназначение;
        
        private IIS.Tabel.DetailArrayOfСоставБриг fСоставБриг;
        
        // *** Start programmer edit section *** (Бригада CustomMembers)

        // *** End programmer edit section *** (Бригада CustomMembers)

        
        /// <summary>
        /// конец.
        /// </summary>
        // *** Start programmer edit section *** (Бригада.конец CustomAttributes)

        // *** End programmer edit section *** (Бригада.конец CustomAttributes)
        [StrLen(255)]
        public virtual string конец
        {
            get
            {
                // *** Start programmer edit section *** (Бригада.конец Get start)

                // *** End programmer edit section *** (Бригада.конец Get start)
                string result = this.fконец;
                // *** Start programmer edit section *** (Бригада.конец Get end)

                // *** End programmer edit section *** (Бригада.конец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бригада.конец Set start)

                // *** End programmer edit section *** (Бригада.конец Set start)
                this.fконец = value;
                // *** Start programmer edit section *** (Бригада.конец Set end)

                // *** End programmer edit section *** (Бригада.конец Set end)
            }
        }
        
        /// <summary>
        /// назначение.
        /// </summary>
        // *** Start programmer edit section *** (Бригада.назначение CustomAttributes)

        // *** End programmer edit section *** (Бригада.назначение CustomAttributes)
        [StrLen(255)]
        public virtual string назначение
        {
            get
            {
                // *** Start programmer edit section *** (Бригада.назначение Get start)

                // *** End programmer edit section *** (Бригада.назначение Get start)
                string result = this.fназначение;
                // *** Start programmer edit section *** (Бригада.назначение Get end)

                // *** End programmer edit section *** (Бригада.назначение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бригада.назначение Set start)

                // *** End programmer edit section *** (Бригада.назначение Set start)
                this.fназначение = value;
                // *** Start programmer edit section *** (Бригада.назначение Set end)

                // *** End programmer edit section *** (Бригада.назначение Set end)
            }
        }
        
        /// <summary>
        /// начало.
        /// </summary>
        // *** Start programmer edit section *** (Бригада.начало CustomAttributes)

        // *** End programmer edit section *** (Бригада.начало CustomAttributes)
        [StrLen(255)]
        public virtual string начало
        {
            get
            {
                // *** Start programmer edit section *** (Бригада.начало Get start)

                // *** End programmer edit section *** (Бригада.начало Get start)
                string result = this.fначало;
                // *** Start programmer edit section *** (Бригада.начало Get end)

                // *** End programmer edit section *** (Бригада.начало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бригада.начало Set start)

                // *** End programmer edit section *** (Бригада.начало Set start)
                this.fначало = value;
                // *** Start programmer edit section *** (Бригада.начало Set end)

                // *** End programmer edit section *** (Бригада.начало Set end)
            }
        }
        
        /// <summary>
        /// Бригада.
        /// </summary>
        // *** Start programmer edit section *** (Бригада.СоставБриг CustomAttributes)

        // *** End programmer edit section *** (Бригада.СоставБриг CustomAttributes)
        public virtual IIS.Tabel.DetailArrayOfСоставБриг СоставБриг
        {
            get
            {
                // *** Start programmer edit section *** (Бригада.СоставБриг Get start)

                // *** End programmer edit section *** (Бригада.СоставБриг Get start)
                if ((this.fСоставБриг == null))
                {
                    this.fСоставБриг = new IIS.Tabel.DetailArrayOfСоставБриг(this);
                }
                IIS.Tabel.DetailArrayOfСоставБриг result = this.fСоставБриг;
                // *** Start programmer edit section *** (Бригада.СоставБриг Get end)

                // *** End programmer edit section *** (Бригада.СоставБриг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бригада.СоставБриг Set start)

                // *** End programmer edit section *** (Бригада.СоставБриг Set start)
                this.fСоставБриг = value;
                // *** Start programmer edit section *** (Бригада.СоставБриг Set end)

                // *** End programmer edit section *** (Бригада.СоставБриг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БригадаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БригадаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БригадаE", typeof(IIS.Tabel.Бригада));
                }
            }
            
            /// <summary>
            /// "БригадаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БригадаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БригадаL", typeof(IIS.Tabel.Бригада));
                }
            }
        }
    }
}
