//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "наименование as \'Наименование\'",
            "код as \'Код\'"})]
    [View("ДолжностьL", new string[] {
            "наименование as \'Наименование\'",
            "код as \'Код\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private string fнаименование;
        
        private string fкод;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// код.
        /// </summary>
        // *** Start programmer edit section *** (Должность.код CustomAttributes)

        // *** End programmer edit section *** (Должность.код CustomAttributes)
        [StrLen(255)]
        public virtual string код
        {
            get
            {
                // *** Start programmer edit section *** (Должность.код Get start)

                // *** End programmer edit section *** (Должность.код Get start)
                string result = this.fкод;
                // *** Start programmer edit section *** (Должность.код Get end)

                // *** End programmer edit section *** (Должность.код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.код Set start)

                // *** End programmer edit section *** (Должность.код Set start)
                this.fкод = value;
                // *** Start programmer edit section *** (Должность.код Set end)

                // *** End programmer edit section *** (Должность.код Set end)
            }
        }
        
        /// <summary>
        /// наименование.
        /// </summary>
        // *** Start programmer edit section *** (Должность.наименование CustomAttributes)

        // *** End programmer edit section *** (Должность.наименование CustomAttributes)
        [StrLen(255)]
        public virtual string наименование
        {
            get
            {
                // *** Start programmer edit section *** (Должность.наименование Get start)

                // *** End programmer edit section *** (Должность.наименование Get start)
                string result = this.fнаименование;
                // *** Start programmer edit section *** (Должность.наименование Get end)

                // *** End programmer edit section *** (Должность.наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.наименование Set start)

                // *** End programmer edit section *** (Должность.наименование Set start)
                this.fнаименование = value;
                // *** Start programmer edit section *** (Должность.наименование Set end)

                // *** End programmer edit section *** (Должность.наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Tabel.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Tabel.Должность));
                }
            }
        }
    }
}
