//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Невыходы.
    /// </summary>
    // *** Start programmer edit section *** (Невыходы CustomAttributes)

    // *** End programmer edit section *** (Невыходы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НевыходыE", new string[] {
            "Дата as \'Дата\'",
            "Состояние as \'Состояние\'"})]
    [View("НевыходыL", new string[] {
            "Дата as \'Дата\'",
            "Состояние as \'Состояние\'"})]
    public class Невыходы : ICSSoft.STORMNET.DataObject
    {
        
        private string fДата;
        
        private IIS.Tabel.Причины fСостояние;
        
        private IIS.Tabel.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Невыходы CustomMembers)

        // *** End programmer edit section *** (Невыходы CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Невыходы.Дата CustomAttributes)

        // *** End programmer edit section *** (Невыходы.Дата CustomAttributes)
        [StrLen(255)]
        public virtual string Дата
        {
            get
            {
                // *** Start programmer edit section *** (Невыходы.Дата Get start)

                // *** End programmer edit section *** (Невыходы.Дата Get start)
                string result = this.fДата;
                // *** Start programmer edit section *** (Невыходы.Дата Get end)

                // *** End programmer edit section *** (Невыходы.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Невыходы.Дата Set start)

                // *** End programmer edit section *** (Невыходы.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Невыходы.Дата Set end)

                // *** End programmer edit section *** (Невыходы.Дата Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Невыходы.Состояние CustomAttributes)

        // *** End programmer edit section *** (Невыходы.Состояние CustomAttributes)
        public virtual IIS.Tabel.Причины Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Невыходы.Состояние Get start)

                // *** End programmer edit section *** (Невыходы.Состояние Get start)
                IIS.Tabel.Причины result = this.fСостояние;
                // *** Start programmer edit section *** (Невыходы.Состояние Get end)

                // *** End programmer edit section *** (Невыходы.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Невыходы.Состояние Set start)

                // *** End programmer edit section *** (Невыходы.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Невыходы.Состояние Set end)

                // *** End programmer edit section *** (Невыходы.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Невыходы.
        /// </summary>
        // *** Start programmer edit section *** (Невыходы.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Невыходы.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Tabel.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Невыходы.Сотрудник Get start)

                // *** End programmer edit section *** (Невыходы.Сотрудник Get start)
                IIS.Tabel.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Невыходы.Сотрудник Get end)

                // *** End programmer edit section *** (Невыходы.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Невыходы.Сотрудник Set start)

                // *** End programmer edit section *** (Невыходы.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Невыходы.Сотрудник Set end)

                // *** End programmer edit section *** (Невыходы.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НевыходыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НевыходыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НевыходыE", typeof(IIS.Tabel.Невыходы));
                }
            }
            
            /// <summary>
            /// "НевыходыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НевыходыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НевыходыL", typeof(IIS.Tabel.Невыходы));
                }
            }
        }
    }
}
