//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabel
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Причины.
    /// </summary>
    // *** Start programmer edit section *** (Причины CustomAttributes)

    // *** End programmer edit section *** (Причины CustomAttributes)
    public enum Причины
    {
        
        // *** Start programmer edit section *** (Причины.Выходной CustomAttributes)

        // *** End programmer edit section *** (Причины.Выходной CustomAttributes)
        Выходной,
        
        // *** Start programmer edit section *** (Причины.Отугл CustomAttributes)

        // *** End programmer edit section *** (Причины.Отугл CustomAttributes)
        Отугл,
        
        // *** Start programmer edit section *** (Причины.Отпуск CustomAttributes)

        // *** End programmer edit section *** (Причины.Отпуск CustomAttributes)
        Отпуск,
        
        // *** Start programmer edit section *** (Причины.Болезнь CustomAttributes)

        // *** End programmer edit section *** (Причины.Болезнь CustomAttributes)
        Болезнь,
        
        // *** Start programmer edit section *** (Причины.Работа CustomAttributes)

        // *** End programmer edit section *** (Причины.Работа CustomAttributes)
        Работа,
    }
}
